
# Clock signal
#Bank = 34, Pin name = ,					Sch name = CLK100MHZ
set_property PACKAGE_PIN P17 [get_ports IN_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports IN_CLK]

#create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk_pin]
#IN_BTN
set_property -dict {PACKAGE_PIN V1 IOSTANDARD LVCMOS33} [get_ports {IN_BTN[0]}]
set_property -dict {PACKAGE_PIN U4 IOSTANDARD LVCMOS33} [get_ports {IN_BTN[1]}]
set_property -dict {PACKAGE_PIN R11 IOSTANDARD LVCMOS33} [get_ports {IN_BTN[2]}]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports {IN_BTN[3]}]
set_property -dict {PACKAGE_PIN R15 IOSTANDARD LVCMOS33} [get_ports {IN_BTN[4]}]


#switch P5 P4 P3 P2 R2 M4 N4 R1 U3 U2 V2 V5 V4 R3 T3 T5
set_property -dict {PACKAGE_PIN P5 IOSTANDARD LVCMOS33} [get_ports {IN_SWITCH[0]}]
set_property -dict {PACKAGE_PIN P4 IOSTANDARD LVCMOS33} [get_ports {IN_SWITCH[1]}]
set_property -dict {PACKAGE_PIN P3 IOSTANDARD LVCMOS33} [get_ports {IN_SWITCH[2]}]
set_property -dict {PACKAGE_PIN P2 IOSTANDARD LVCMOS33} [get_ports {IN_SWITCH[3]}]
set_property -dict {PACKAGE_PIN R2 IOSTANDARD LVCMOS33} [get_ports {IN_SWITCH[4]}]
set_property -dict {PACKAGE_PIN M4 IOSTANDARD LVCMOS33} [get_ports {IN_SWITCH[5]}]
set_property -dict {PACKAGE_PIN N4 IOSTANDARD LVCMOS33} [get_ports {IN_SWITCH[6]}]
set_property -dict {PACKAGE_PIN R1 IOSTANDARD LVCMOS33} [get_ports {IN_SWITCH[7]}]
set_property -dict {PACKAGE_PIN U3 IOSTANDARD LVCMOS33} [get_ports {IN_SWITCH[8]}]
set_property -dict {PACKAGE_PIN U2 IOSTANDARD LVCMOS33} [get_ports {IN_SWITCH[9]}]
set_property -dict {PACKAGE_PIN V2 IOSTANDARD LVCMOS33} [get_ports {IN_SWITCH[10]}]
set_property -dict {PACKAGE_PIN V5 IOSTANDARD LVCMOS33} [get_ports {IN_SWITCH[11]}]
set_property -dict {PACKAGE_PIN V4 IOSTANDARD LVCMOS33} [get_ports {IN_SWITCH[12]}]
set_property -dict {PACKAGE_PIN R3 IOSTANDARD LVCMOS33} [get_ports {IN_SWITCH[13]}]
set_property -dict {PACKAGE_PIN T3 IOSTANDARD LVCMOS33} [get_ports {IN_SWITCH[14]}]
set_property -dict {PACKAGE_PIN T5 IOSTANDARD LVCMOS33} [get_ports {IN_SWITCH[15]}]

#LED F6 G4 G3 J4 H4 J3 J2 K2 K1 H6 H5 J5 K6 L1 M1 K3
set_property -dict {PACKAGE_PIN F6 IOSTANDARD LVCMOS33} [get_ports {OUT_LED[0]}]
set_property -dict {PACKAGE_PIN G4 IOSTANDARD LVCMOS33} [get_ports {OUT_LED[1]}]
set_property -dict {PACKAGE_PIN G3 IOSTANDARD LVCMOS33} [get_ports {OUT_LED[2]}]
set_property -dict {PACKAGE_PIN J4 IOSTANDARD LVCMOS33} [get_ports {OUT_LED[3]}]
set_property -dict {PACKAGE_PIN H4 IOSTANDARD LVCMOS33} [get_ports {OUT_LED[4]}]
set_property -dict {PACKAGE_PIN J3 IOSTANDARD LVCMOS33} [get_ports {OUT_LED[5]}]
set_property -dict {PACKAGE_PIN J2 IOSTANDARD LVCMOS33} [get_ports {OUT_LED[6]}]
set_property -dict {PACKAGE_PIN K2 IOSTANDARD LVCMOS33} [get_ports {OUT_LED[7]}]
set_property -dict {PACKAGE_PIN K1 IOSTANDARD LVCMOS33} [get_ports {OUT_LED[8]}]
set_property -dict {PACKAGE_PIN H6 IOSTANDARD LVCMOS33} [get_ports {OUT_LED[9]}]
set_property -dict {PACKAGE_PIN H5 IOSTANDARD LVCMOS33} [get_ports {OUT_LED[10]}]
set_property -dict {PACKAGE_PIN J5 IOSTANDARD LVCMOS33} [get_ports {OUT_LED[11]}]
set_property -dict {PACKAGE_PIN K6 IOSTANDARD LVCMOS33} [get_ports {OUT_LED[12]}]
set_property -dict {PACKAGE_PIN L1 IOSTANDARD LVCMOS33} [get_ports {OUT_LED[13]}]
set_property -dict {PACKAGE_PIN M1 IOSTANDARD LVCMOS33} [get_ports {OUT_LED[14]}]
set_property -dict {PACKAGE_PIN K3 IOSTANDARD LVCMOS33} [get_ports {OUT_LED[15]}]

#7 segment display
set_property PACKAGE_PIN B4 [get_ports {OUT_SEG0DATA[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUT_SEG0DATA[0]}]
set_property PACKAGE_PIN A4 [get_ports {OUT_SEG0DATA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUT_SEG0DATA[1]}]
set_property PACKAGE_PIN A3 [get_ports {OUT_SEG0DATA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUT_SEG0DATA[2]}]
set_property PACKAGE_PIN B1 [get_ports {OUT_SEG0DATA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUT_SEG0DATA[3]}]
set_property PACKAGE_PIN A1 [get_ports {OUT_SEG0DATA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUT_SEG0DATA[4]}]
set_property PACKAGE_PIN B3 [get_ports {OUT_SEG0DATA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUT_SEG0DATA[5]}]
set_property PACKAGE_PIN B2 [get_ports {OUT_SEG0DATA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUT_SEG0DATA[6]}]

set_property PACKAGE_PIN D5 [get_ports {OUT_SEG0DP}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUT_SEG0DP}]

set_property PACKAGE_PIN G2 [get_ports {OUT_SEG0SELE[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUT_SEG0SELE[0]}]
set_property PACKAGE_PIN C2 [get_ports {OUT_SEG0SELE[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUT_SEG0SELE[1]}]
set_property PACKAGE_PIN C1 [get_ports {OUT_SEG0SELE[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUT_SEG0SELE[2]}]
set_property PACKAGE_PIN H1 [get_ports {OUT_SEG0SELE[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUT_SEG0SELE[3]}]

set_property PACKAGE_PIN D4 [get_ports {OUT_SEG1DATA[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUT_SEG1DATA[0]}]
set_property PACKAGE_PIN E3 [get_ports {OUT_SEG1DATA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUT_SEG1DATA[1]}]
set_property PACKAGE_PIN D3 [get_ports {OUT_SEG1DATA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUT_SEG1DATA[2]}]
set_property PACKAGE_PIN F4 [get_ports {OUT_SEG1DATA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUT_SEG1DATA[3]}]
set_property PACKAGE_PIN F3 [get_ports {OUT_SEG1DATA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUT_SEG1DATA[4]}]
set_property PACKAGE_PIN E2 [get_ports {OUT_SEG1DATA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUT_SEG1DATA[5]}]
set_property PACKAGE_PIN D2 [get_ports {OUT_SEG1DATA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUT_SEG1DATA[6]}]

set_property PACKAGE_PIN H2 [get_ports {OUT_SEG1DP}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUT_SEG1DP}]

set_property PACKAGE_PIN G1 [get_ports {OUT_SEG1SELE[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUT_SEG1SELE[0]}]
set_property PACKAGE_PIN F1 [get_ports {OUT_SEG1SELE[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUT_SEG1SELE[1]}]
set_property PACKAGE_PIN E1 [get_ports {OUT_SEG1SELE[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUT_SEG1SELE[2]}]
set_property PACKAGE_PIN G6 [get_ports {OUT_SEG1SELE[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUT_SEG1SELE[3]}]
